services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      args:
        - PACKAGE_NAME=@syllogi/server
        - POSTGRES_HOST="rate_db"
    ports:
      - "5000:5000"
    depends_on:
      - rate-db
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
      args:
        - PACKAGE_NAME=@syllogi/client
    ports:
      - "3000:80"
    command: [nginx, "-g", "daemon off;"]
  rate-db:
    container_name: rate_db
    environment:
      - POSTGRES_DB=rate
      - POSTGRES_USER=rate
      - POSTGRES_PASSWORD=rate
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
